name = "globalgroundsnews"
compatibility_date = "2024-09-27"  # Current date

[build]
command = "npm run build"  # The build command for your Next.js project

[site]
bucket = "./.next"  # This points to the Next.js output directory containing static assets
entry-point = "./workers"  # Points to your worker directory where the service worker logic is handled
exclude = ["cache/webpack/server-production/*"]  # Exclude all large pack files

[env.production]
account_id = "6e6777f3fa1e7f73bdeda9d13cb3dbd3"  # Replace with your Cloudflare account ID
project_name = "globalgroundsnews"
route = "https://globalgrounds.news/*"  # Replace with your actual domain route

[worker]
type = "javascript"  # Ensure this is correctly configured for your JavaScript-based worker

[vars]
NODE_ENV = "production"  # Set any environment variables needed for production

[experimental]
pages_build_output_dir = "./.next"  # This is required to ensure that Cloudflare Pages reads the correct output directory for Pages hosting